### PR TITLE
Update GL-DPPD-7112.md

### PR DESCRIPTION
**Pull request by J-81**
Bring DPPD in sync with NF_MAAgilent1ch_1.0.0-RC6

### CODE REVIEW

**Comment by J-81** [comment]
In sync with 1.0.0-RC7/1.0.0 Official (same thing, different tags)

**Comment by asaravia-butler** [comment]
@J-81 , it looks like all these changes are already on master. Can this PR be closed?

**Review by Abdurahmon0412 — APPROVED** [review]

**Comment by Abdurahmon0412** [comment]
You must resolve this conflict

**Comment by torres-alexis** [comment]
Changes in the DPPD documentation were implemented through the following commits ending on March 21, 2023:
- 53bdf3d370a9214fdd3c84990a3ef07da3bc086c
- ee385e5902ca299e3018a1be816bf59081ebe670
- 8e1cd819d97a4fa4817d9568efc36c43202d746f
- f7c1ba3e599b3b19436ca3bd72767436641da7a0
- c05529331a7787280f956d8cd98f2a487a6973c8
- 9eb6316ac99d7bf6e17a0d405bc295a9dd0e0824
- 19e2de2903ee9fbef90613bd6d7270e8042a9cd4

Microarray files changes and commit history were merged in from the development fork through pull request #63.

This PR can be closed without merging.

**Pull request closed without merging**
